name: Assigns a milestone

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  push:
    branches: [ add/auto-assign-milestone ]

jobs:
  open:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get latest milestone data
        run: .github/get-milestone.sh

      - name: Assigns milestone
        uses: actions/github-script@v2
        with:
          script: |
            console.log( context.issue.number );
            await github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              milestone: ${{ env.MILESTONE_NUMBER }},
            })
