name: Assigns a milestone

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  push:
    branches: [ add/auto-assign-milestone ]

jobs:
  open:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest milestone data
        uses: actions/github-script@v2
        id: milestone-data
        with:
          script: |
            console.log(await github.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
            }))



