name: Assigns a milestone to new issues and PRs

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened
  push:
    branches: [ add/auto-assign-milestone ]

jobs:
  open:
    runs-on: ubuntu-latest

    steps:
      - name: Get latest milestone data
        uses: actions/github-script@v2
        id: milestone-data
        with:
          script: |
            github.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })

      - name: Outputs result
        run: echo "${{ steps.milestone-data.outputs.result }}"


