name: Deploy to staging

on:
  push:
    branches: [ master, use-deploy-fork ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy
      uses: Automattic/FTP-Deploy-Action@3.0.1
      with:
        ftp-server: sftp://ssh.atomicsites.net/htdocs/
        ftp-username: ${{ secrets.SFTP_USERNAME }}
        ftp-password: ${{ secrets.SFTP_PASSWORD }}
        known-hosts: "ssh.atomicsites.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDwfT/YEhOKO2Z0+XrjRqUS5Q2Ali6AlhOhZtzlIfMOvm03SypeDJH70tlUHasS+nm0SnZ01fOiEeAXa91ZhMihIYUT3nTGuiA2J3uVYsySCJefvhWc0kg1FbEus3V3cVmx4e3XctdkzLbOgPNngypZocbP+8yCpbx6Kb9lihmgTjgGn2QzbK1enRSzsN/CbjVhej9jwukbrWqdCrQsKAsoZ2p6YCtcKbHS+Yy4RwcO9PxZUBkeMXUrejms027bRcdVfwf55hWSD9xYEHpEHupkSL4ofWs3UKeRGz+jCCzl7Nu0S6VSwK4Zzll0auHI0Hwh8WKTJbSn1gxCdF93/rmP"
