name: Package theme for release

on:
  release:
    types: [ created ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Gets Yarn cache path
      id: yarn-cache-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - uses: actions/cache@v1
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Installs dependencies
      run: yarn install --frozen-lockfile --non-interactive

    - name: Builds blocks
      run: yarn build

    - name: Package zip file
      run: zip -rv mutualaidnyc.zip . -x $(awk '{print "/" $0 "*"}' .git-ftp-ignore | tr '\n' ' ')

    - uses: actions/upload-artifact@v2
      with:
        name: mutualaidnyc.zip
        path: mutualaidnyc.zip

    # - name: Upload the artifacts
    #   uses: skx/github-action-publish-binaries@master
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     args: mutualaidnyc.zip
